name: Java CI with Maven

on: pull_request

jobs:
  # Building to jar
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Appimage with jpackage
        run: |
          pwd
          ls
          ls target/
          jpackage --input oel-remake/ --main-jar target/oel-remake.jar --main-class Application --type app-image --dest app-image

      - name: Test
        run: |
          cd ..
          pwd
          ls

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: appimage
          path: ../app-image/Application/bin/Application

