name: Super-Linter

on: pull_request

jobs:
    super-lint:
        name: Lint code base
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.7

            - name: Run Super-Linter
              uses: github/super-linter@v6
              env:
                DEFAULT_BRANCH: ${{ github.event.pull_request.base.ref }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}